### ISSUE TITLE
Can not `go get -u github.com/favclip/jwg/cmd/jwg`

### ISSUE THREAD

**Issue by kubosho** [favclip/jwg#3]
Go version: go1.6 darwin/amd64
    
error message:
```
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/Cellar/go/1.6/libexec/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/Users/s.kubota/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
```

`gcimporter` is not found in GitHub and godoc, but `gcimporter15` found.

**not found:**
- https://github.com/golang/tools/tree/master/go/gcimporter
- https://godoc.org/golang.org/x/tools/go/gcimporter

**found:**
- https://github.com/golang/tools/tree/master/go/gcimporter15
- https://godoc.org/golang.org/x/tools/go/gcimporter15

**Comment by mstssk** [comment]
FYR https://github.com/golang/tools/commit/adaaa074861b0d254acf51dec74daf7c2ba20e90
This commit deleted `gcimporter` directory.

**Comment by vvakame** [comment]
good informations! thanks a lot.
